version: '3'
services:
  maria_db:
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: integration_v1
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  integration:
    build: .
    depends_on:
      - kafka
      - zookeeper
      - maria_db